version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/flaskdb
    depends_on:
      - redis
      - db
    command: ["python", "app.py"]

  celery:
    build: .
    container_name: celery_worker
    depends_on:
      - redis
      - db
    environment:
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/flaskdb
    command: ["celery", "-A", "app.celery", "worker", "--loglevel=info"]

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flaskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
